### ISSUE TITLE
Issue with recv() in examples

### ISSUE THREAD

**Issue by tylerburleigh** [vdv7/stap#1]
I was experimenting with some of the examples, and I noticed that they seem to get stuck when executing a call to the recv() function. 

For example, the sht.py example program gets stuck after presenting response feedback on the first trial, presumably because of the recv() call on line 69. Here's an example from the log file output:

> 1480196296567	0	{"_replace": {"OBJ": "Is this object a Greeble or a Groble?"}}
> 1480196296570	0	{"_task": {"good": {"_pp": "Correct"}, "bad": {"_pp": "Incorrect"}, "end": {"Trial": 32}}}
> 1480196296570	0	{"Trial": {"_nm": {"<=": 32}}}
> 1480196296571	0	{"OBJ": ""}
> 1480196296571	0	{"#btns": ["_i", "Groble", "Greeble"]}
> 1480196296571	0	{"Trial": 1}
> 1480196296571	0	{"OBJ": {"_bx": {"bd": "solid", "r": 0, "bg": "black", "bdc": "red", "bdw": 10, "w": 20, "h": 20, "pad": 0}}}
> 1480196298216	1	[1924,"#btns",{"Greeble":3}]
> 1480196298216	0	{"_pp": "Correct"}
> 1480196298217	0	{"_S": 2424, "_R": 0}

Similarly, the _math.py program gets stuck after the user submits an answer to the first math problem, presumably because of the recv() call on line 25. Again, from the log file:

> 1480197220529	0	{"_task": {"bad": {"#feedback": "Incorrect"}, "good": {"#feedback": "Correct"}}}
> 1480197220532	0	{"Add these numbers": {"#": 9}}
> 1480197220532	0	{"Add these numbers": {"+": 9}}
> 1480197220532	0	{"Answer": {"_ix": {}}}
> 1480197220532	0	{"#submit": {"Submit": 1, "_i": {}}}
> 1480197223048	1	[2767,"Answer","18"]

Any idea what might be causing this? Thanks!

**Comment by tylerburleigh** [comment]
By the way, if it helps I've got a remote server running stap with this issue:

http://138.197.23.155/taskServer/shj.htm

**Comment by vdv7** [comment]
thanks for that.i believe i fixed the problem, try updating your repo( line 1005 changed in examples/taskServer/lib/stap.js )
  
|  
|   
|   
|   |    |

   |

  |
|  
|    |  
vdv7/stap
 stap - Simple Task-Actor Protocol  |   |

  |

  |

 
 

    On Sunday, November 27, 2016 5:42 PM, tylerburleigh <notifications@github.com> wrote:
 

 By the way, if it helps I've got a remote server running stap with this issue:http://138.197.23.155/taskServer/shj.htm—

**Comment by tylerburleigh** [comment]
Thanks, that worked!
